name: trap_analysis
channels:
  - defaults
dependencies:
  - ca-certificates=2019.1.23=0
  - certifi=2019.3.9=py37_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - ncurses=6.1=he6710b0_1
  - openssl=1.1.1b=h7b6447c_1
  - pip=19.1=py37_0
  - python=3.7.3=h0371630_0
  - readline=7.0=h7b6447c_5
  - setuptools=41.0.1=py37_0
  - sqlite=3.28.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.33.1=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - chardet==3.0.4
    - conda==4.3.16
    - conda-autoenv==0.1
    - idna==2.8
    - pycosat==0.6.3
    - requests==2.21.0
    - ruamel-yaml==0.15.94
    - urllib3==1.24.3
prefix: /home/jmsung/miniconda/envs/trap_analysis


